### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by acs-ferreira**
- Tested OK on PS v1.6.1.10
- Link to official logo :)

### CODE REVIEW

**Comment by firstred** [comment]
Thanks for the text corrections, but why the link to an external image? What if Stripe updates the image location?

**Comment by acs-ferreira** [comment]
True, why not simply use the official logo instead of https://github.com/firstred/mdstripe/blob/dev/views/img/stripebtnlogo.png

**Comment by firstred** [comment]
I'd rather not include that many image.s

**Comment by firstred** [comment]
Thank you!

**Pull request merged**
